version: 0.2

env:
    variables:
        CACHE_CONTROL: "86400"
        S3_BUCKET: "{{s3_bucket_url}}"
        BUILD_FOLDER: "dist"
phases:
    install:
        runtime-versions:
            nodejs: 16
        commands:
            - echo Installing source NPM dependencies...
            - cd web-devotee
            - npm install
            - npm install -g @angular/cli
    build:
        commands:
            - echo Build started on `date`
            - ng build
artifacts:
    files:
        - '**/*'
        - 'dist/*'
        - 'dist'

    base-directory: 'dist*'
    discard-paths: yes
